//! Enriches exported schemas with links to the tmux manual.

use serde_json::Value;

const TMUX_MANUAL_URL: &str = "https://man.openbsd.org/tmux";

/// (operationId, tmux-command-anchor)
const OPERATION_DOCS: &[(&str, &str)] = &[
    ("ls", "list-sessions"),
    ("new", "new-session"),
    ("kill_session", "kill-session"),
    ("kill_window", "kill-window"),
    ("kill_pane", "kill-pane"),
    ("list_windows", "list-windows"),
    ("list_panes", "list-panes"),
    ("send_keys", "send-keys"),
    ("rename_session", "rename-session"),
    ("rename_window", "rename-window"),
    ("new_window", "new-window"),
    ("split_window", "split-window"),
    ("capture_pane", "capture-pane"),
    ("capture_pane_with_options", "capture-pane"),
    ("create_session_with_windows", "new-session"),
    ("swap_panes", "swap-pane"),
    ("move_window", "move-window"),
    ("select_window", "select-window"),
    ("select_pane", "select-pane"),
    ("resize_pane", "resize-pane"),
    ("select_layout", "select-layout"),
    ("get_option", "show-options"),
    ("set_option", "set-option"),
    ("list_options", "show-options"),
];

/// (schema name, description text)
const SCHEMA_DOCS: &[(&str, &str)] = &[
    (
        "SessionResponse",
        "A tmux session. See: https://man.openbsd.org/tmux#CLIENTS_AND_SESSIONS",
    ),
    (
        "NewSessionResponse",
        "A tmux session. See: https://man.openbsd.org/tmux#CLIENTS_AND_SESSIONS",
    ),
    (
        "WindowResponse",
        "A tmux window. See: https://man.openbsd.org/tmux#WINDOWS_AND_PANES",
    ),
    (
        "NewWindowResponse",
        "A tmux window. See: https://man.openbsd.org/tmux#WINDOWS_AND_PANES",
    ),
    (
        "PaneResponse",
        "A tmux pane. See: https://man.openbsd.org/tmux#WINDOWS_AND_PANES",
    ),
    (
        "SplitWindowResponse",
        "A tmux pane created by split-window. See: https://man.openbsd.org/tmux#split-window",
    ),
    (
        "OptionResponse",
        "A tmux option. See: https://man.openbsd.org/tmux#OPTIONS",
    ),
    (
        "CapturePaneResponse",
        "Response containing captured pane content. See: https://man.openbsd.org/tmux#capture-pane",
    ),
];

/// Enrich an OpenAPI JSON value with tmux documentation links.
pub fn enrich_openapi(spec: &mut Value) {
    // Top-level externalDocs
    spec["externalDocs"] = serde_json::json!({
        "description": "tmux manual",
        "url": TMUX_MANUAL_URL,
    });

    // Per-operation externalDocs
    if let Some(paths) = spec.get_mut("paths").and_then(|v| v.as_object_mut()) {
        for (_path, path_item) in paths.iter_mut() {
            for method in &["get", "post", "put", "delete", "patch"] {
                if let Some(operation) = path_item.get_mut(method) {
                    if let Some(op_id) = operation.get("operationId").and_then(|v| v.as_str()) {
                        if let Some((_, tmux_cmd)) =
                            OPERATION_DOCS.iter().find(|(id, _)| *id == op_id)
                        {
                            operation["externalDocs"] = serde_json::json!({
                                "description": format!("tmux {tmux_cmd}"),
                                "url": format!("{TMUX_MANUAL_URL}#{tmux_cmd}"),
                            });
                        }
                    }
                }
            }
        }
    }

    // Schema descriptions
    if let Some(schemas) = spec
        .pointer_mut("/components/schemas")
        .and_then(|v| v.as_object_mut())
    {
        for (name, desc) in SCHEMA_DOCS {
            if let Some(schema) = schemas.get_mut(*name) {
                schema["description"] = Value::String(desc.to_string());
            }
        }
    }
}

/// Enrich a proto string with tmux documentation comments.
///
/// The proto generated by the `grpc_service!` macro already includes
/// doc comments on the service and RPCs. This function adds comments
/// to message definitions that represent domain types.
pub fn enrich_proto(proto: &str) -> String {
    let message_docs: &[(&str, &str)] = &[
        (
            "message TmuxSession {",
            "// A tmux session. See: https://man.openbsd.org/tmux#CLIENTS_AND_SESSIONS",
        ),
        (
            "message TmuxWindow {",
            "// A tmux window. See: https://man.openbsd.org/tmux#WINDOWS_AND_PANES",
        ),
        (
            "message TmuxPaneMsg {",
            "// A tmux pane. See: https://man.openbsd.org/tmux#WINDOWS_AND_PANES",
        ),
        (
            "message GetOptionRequest {",
            "// A tmux option. See: https://man.openbsd.org/tmux#OPTIONS",
        ),
        (
            "message TmuxOptionMsg {",
            "// A tmux option (name-value pair with scope). See: https://man.openbsd.org/tmux#OPTIONS",
        ),
    ];

    let mut result = String::with_capacity(proto.len() + 512);
    for line in proto.lines() {
        let trimmed = line.trim();
        if let Some((_, comment)) = message_docs.iter().find(|(marker, _)| trimmed == *marker) {
            result.push_str(comment);
            result.push('\n');
        }
        result.push_str(line);
        result.push('\n');
    }
    // Ensure no trailing newline beyond what the original had
    if !proto.ends_with('\n') && result.ends_with('\n') {
        result.pop();
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn enrich_openapi_adds_top_level_external_docs() {
        let mut spec: Value = serde_json::json!({"openapi": "3.1.0", "paths": {}});
        enrich_openapi(&mut spec);
        assert_eq!(spec["externalDocs"]["url"], TMUX_MANUAL_URL);
        assert_eq!(spec["externalDocs"]["description"], "tmux manual");
    }

    #[test]
    fn enrich_openapi_adds_operation_external_docs() {
        let mut spec: Value = serde_json::json!({
            "paths": {
                "/ls": {
                    "get": {
                        "operationId": "ls"
                    }
                }
            }
        });
        enrich_openapi(&mut spec);
        let ext = &spec["paths"]["/ls"]["get"]["externalDocs"];
        assert_eq!(ext["description"], "tmux list-sessions");
        assert_eq!(ext["url"], "https://man.openbsd.org/tmux#list-sessions");
    }

    #[test]
    fn enrich_openapi_adds_schema_descriptions() {
        let mut spec: Value = serde_json::json!({
            "paths": {},
            "components": {
                "schemas": {
                    "SessionResponse": {"type": "object"},
                    "PaneResponse": {"type": "object"}
                }
            }
        });
        enrich_openapi(&mut spec);
        assert!(
            spec["components"]["schemas"]["SessionResponse"]["description"]
                .as_str()
                .unwrap()
                .contains("CLIENTS_AND_SESSIONS")
        );
        assert!(
            spec["components"]["schemas"]["PaneResponse"]["description"]
                .as_str()
                .unwrap()
                .contains("WINDOWS_AND_PANES")
        );
    }

    #[test]
    fn enrich_proto_adds_message_comments() {
        let proto = "message TmuxSession {\n  string id = 1;\n}\n";
        let enriched = enrich_proto(proto);
        assert!(enriched.contains(
            "// A tmux session. See: https://man.openbsd.org/tmux#CLIENTS_AND_SESSIONS\nmessage TmuxSession {"
        ));
    }

    #[test]
    fn enrich_proto_does_not_duplicate_existing_comments() {
        let proto = "// existing\nmessage Foo {\n}\n";
        let enriched = enrich_proto(proto);
        // Foo is not in our docs list, so should be unchanged
        assert_eq!(enriched, proto);
    }
}
